using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace InterviewQuestions.LeetCode
{
    class FindTheDifferenceClass
    {
        /// <summary>
        /// Given two strings s and t which consist of only lowercase letters.
        //  String t is generated by random shuffling string s and then add one more letter at a random position.
        //  Find the letter that was added in t.
        //  Example:
        //  Input:
        //  s = "abcd"
        //  t = "abcde"
        //  Output:
        //  e
        //  Explanation:
        //  'e' is the letter that was added.
        //  </summary>
        //  <param name="s"></param>
        //  <param name="t"></param>
        /// <returns></returns>
        public static char FindDiff(string s, string t)
        {
            // Initially, char code is the last t character, since that won't be included in the loop
            int charCode = t[t.Length - 1];

            // For all positions (except the "bonus" one handled above), change running char total
            for (int i = 0; i < s.Length; i++)
            {
                charCode -= s[i];
                charCode += t[i];
            }

            return (char)charCode;
        }

    }
}
